### ISSUE TITLE
Pending reloading should be canceled if new change is detected

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/gradle-environment-plugin#4]
to avoid reloading twice unnecessarily when using `environmentDev` task

**Comment by mierzwid** [comment]
I thought to rewrite this code to use Flow - it would be possible, but will take lots of time and require reworking the entire solution. It would require changes in the common plugin alongside the environment plugin. 

It looks to me, that problem was created when we moved from a single container - dispatcher, to support multiple containers. Because of that, we do not aggregate events anymore as we did before because we don't know if all the following events that wait to be digested are related to the same container or a different one.

The only solution would be to separate flows of events related to different containers and then reload only once for a set of changes that happened.

**Comment by pun-ky** [comment]
> the last reload hasn't damaged anything.  
>  

but I think that reload should be idempotent so it could be canceled at any time. 

and that's the case
